name: FwindEmikoCore
version: '0.6'
main: top.miragedge.fwindemikocore.FwindEmikoCore
api-version: '1.21'
author: F.windEmiko
depend: [CraftEngine]
softdepend: [ProtocolLib, PlaceholderAPI]
commands:
  fwindemikocore:
    description: FwindEmikoCore 主命令
    usage: /fwindemikocore <info|reload>
    aliases: [fec]
permissions:
  fwindemikocore.admin:
    description: 允许使用重载命令
    default: op
